### ISSUE TITLE
Request for Data Preprocessing Code

### ISSUE THREAD

**Issue by erasmeyu** [LeonardoBerti07/Deep-Learning-Algorithms-for-financial-time-serie-forecasting-#1]
Hi, could you please provide more details about the data preprocessing code?

Your project closely aligns with my research interests, I believe that incorporating some of your methodologies, especially the data preprocessing techniques, could significantly enhance the quality of my work. I have thoroughly reviewed your repository, but I noticed that the code for data preprocessing is not available. 

Thank you very much for considering my request.

**Comment by LeonardoBerti00** [comment]
Hi, unfortunately, I can't refind the pre-processing files of this particular project, in https://github.com/matteoprata/LOBCAST you can find some pre-processing of LOB data, but idk if there is what you need.
Anyway, the pre-processing consists simply of appending the trading csv files and applying z-score normalization.

**Comment by erasmeyu** [comment]
> Hi, unfortunately, I can't refind the pre-processing files of this particular project, in https://github.com/matteoprata/LOBCAST you can find some pre-processing of LOB data, but idk if there is what you need. Anyway, the pre-processing consists simply of appending the trading csv files and applying z-score normalization.

Hi, thanks for your sharing. LOBCAST is really wonderful resource. But do you know the launch time of new version LOBCAST, as it's said it would be updated month ago.  Many thanks for your reply.

**Comment by LeonardoBerti00** [comment]
I'm very sorry for the waiting but we had some problems. Anyway, the new version would be simply a refactoring for better usability and readability. If you need some explanations or help on using the current version please email me at leonardo.berti07@gmail.com and i would be happy to help you.
